version: '3'
services:
  mysql:
    image: mysql:5.5.62 # here you can use latest version of mysql also , depending on your requirement
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./telemysql_data:/var/lib/mysql
      - /var/www/html:/var/www/html
    ports:
      - "3307:3306"  # Map port 3307 on the host to port 3306 in the container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - UPLOAD_LIMIT=512M
    links:
      - mysql:db
    ports:
      - "99:80"

  my_apache_php:
    image: docker.io/kmahesh541/php5-apache2-mysql5
    restart: unless-stopped
    volumes:
      - /var/www/html:/var/www/html
      - /var/www:/var/www
    ports:
      - "88:80"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}


#docker-compose up -d
